name: Build e Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurando o java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Configurando o banco de dados
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: 'contratos'
          postgresql user: 'postgres'
          postgresql password: 'admin'
      - name: Permiss√£o para executar o gradlew
        run: chmod +x ./contrato/gradlew
      - name: Deploy no Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "contratos-1" #Must be unique in Heroku
          heroku_email: "william.costa@escolar.ifrn.edu.br"
          usedocker: "true"
